# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "colorize", "~> 0.8.1"

gem "tty-prompt", "~> 0.23.1"

gem "json", "~> 2.5"



gem "optparse", "~> 0.1.1"


gem "ruby_figlet", "~> 0.6.1"

gem "rspec", "~> 3.10"
